//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///   {
        ///      &quot;Id&quot;: 1,
        ///      &quot;Name&quot;: &quot;Bagels and Cream Cheese&quot;,
        ///      &quot;Description&quot;: &quot;Authentic New York-style bagels.  Start the day with freshly baked batches and your favorite cream cheese.&quot;,
        ///      &quot;Price&quot;: 7.49,
        ///      &quot;Type&quot;: &quot;Breakfast&quot;,
        ///      &quot;ImageUri&quot;: &quot;breakfast_bagel.jpg&quot;
        ///   },
        ///   {
        ///      &quot;Id&quot;: 2,
        ///      &quot;Name&quot;: &quot;Kellog&apos;s Honey Buzz Cereal&quot;,
        ///      &quot;Description&quot;: &quot;A bowl of Honey Smacks with honey, toasted pecans and banana chips.&quot;,
        ///      &quot;Price&quot;: 6.99,
        ///      &quot;Type&quot;: &quot;Breakfast&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string menu_json {
            get {
                return ResourceManager.GetString("menu_json", resourceCulture);
            }
        }
    }
}
